language: node_js
node_js:
  - 6
  - 7

before_install:
  - curl "https://install.meteor.com/?release=1.4.2.7"
  - export PATH="$HOME/.meteor:$PATH"
  - sudo apt-get install python
  - sudo apt-get install make
  - sudo apt-get install g++

before_script:
  - meteor npm install node-gyp -g
  - meteor npm install

script:
  - meteor build $HOME/build.tgz