language: node_js
node_js:
  - 6
  - 7

before_install:
  - curl "https://install.meteor.com/?release=1.4.2.7"
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules
    - .meteor

before_script:
  - meteor npm install node-gyp -g
  - meteor npm install --dev

script:
  - meteor npm run test
  - meteor build $HOME/build.tgz